# https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs
defaults: &defaults
  docker:
    - image: quay.io/pantheon-public/php-ci:2.x
  working_directory: ~/terminus_build_tools_plugin
  environment:

    #=========================================================================
    # In addition to the environment variables defined in this file, also
    # add the following variables in the Circle CI UI.
    #
    # See: https://circleci.com/docs/2.0/env-vars/
    #
    # TERMINUS_SITE:  Name of the Pantheon site to run tests on, e.g. my_site
    # TERMINUS_TOKEN: The Pantheon machine token
    # TERMINUS_ORG:   Name of Pantheon Agency / Team
    # CIRCLE_TOKEN:   Circle CI Token
    # GITHUB_TOKEN:   The GitHub personal access token
    # GITHUB_USER:    The GitHub username
    # GIT_EMAIL:      The email address to use when making commits
    # BITBUCKET_USER: The Bitbucket Username
    # BITBUCKET_PASS: The Bitbucket app specific password
    #
    # TEST_SITE_NAME: The name of the test site to provide when installing.
    # ADMIN_PASSWORD: The admin password to use when installing.
    # ADMIN_EMAIL:    The email address to give the admin when installing.
    #=========================================================================

    BASH_ENV: ~/.bashrc
    TZ: "/usr/share/zoneinfo/America/Chicago"
    TERM: dumb

version: 2
jobs:
  # @todo: common initialization, maybe
  unit:
    <<: *defaults
    steps:
      - run: echo "No unit tests yet."
      - checkout

      - restore_cache:
          keys:
              - composer-cache

#      - run:
#          name: setup-environment-vars
#          command: /build-tools-ci/scripts/set-environment

      - run:
          name: log in
          command: terminus -n auth:login --machine-token="$TERMINUS_TOKEN"

      - run:
          name: install dev dependencies, build assets, etc.
          command: ./.ci/scripts/01-prepare

      - run:
          name: build assets
          command: composer -n build-assets

      - run:
          name: prepare database for site-under test
          command: ./.ci/scripts/02-init-site-under-test-clone-existing
          # command: ./.ci/scripts/02-init-site-under-test-reinstall-new

      - run:
          name: run composer install again to get dev dependencies
          command: composer install

      #- run:
      #    name: run functional tests with Behat
      #    command: ./.ci/scripts/03-test

      - run:
          name: post-test actions
          command: ./.ci/scripts/04-post-test

      - run:
          name: handle merge to master (if needed)
          command: ./.ci/scripts/05-merge-master

      - run:
          name: remove transient test fixtures
          command: ./.ci/scripts/09-cleanup-fixtures

  test_drupal_8_github:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: dependencies
          command: ./.circleci/set-up-globals.sh
      - run:
          name: Check Terminus version
          command: terminus --version
      - run:
          name: Test D8 with GitHub
          command: ./.circleci/test-example-repo.sh "pantheon-systems/example-drops-8-composer:dev-master" github
      - run:
          name: Clean up D8 GitHub fixtures after pass
          command: ./.circleci/cleanup-fixtures.sh ok
      - run:
          name: Clean up D8 GitHub fixtures after failure
          when: on_fail
          command: ./.circleci/cleanup-fixtures.sh fail

workflows:
  version: 2
  build_test:
    jobs:
      - unit
      - test_drupal_8_github:
          requires:
            - unit

