# Schema for the configuration files of the Link module.

field.formatter.settings.citizen_custom:
  type: mapping
  label: 'Citizen Custom Link format settings'
  mapping:
    trim_length:
      type: integer
      label: 'Trim link text length'
    url_only:
      type: boolean
      label: 'URL only'
    url_plain:
      type: boolean
      label: 'Show URL as plain text'
    rel:
      type: string
      label: 'Add rel="nofollow" to links'
    target:
      type: string
      label: 'Open link in new window'

field.formatter.settings.citizen_custom_separate:
  type: field.formatter.settings.citizen_custom
  label: 'Citizen Custom Link format settings'

field.widget.settings.citizen_custom_default:
  type: mapping
  label: 'Citizen Custom Link format settings'
  mapping:
    placeholder_url:
      type: string
      label: 'Placeholder for URL'
    placeholder_title:
      type: label
      label: 'Placeholder for link text'

field.storage_settings.citizen_custom:
  type: mapping
  label: 'Citizen Custom Link settings'

field.field_settings.citizen_custom:
  type: mapping
  label: 'Citizen Custom Link settings'
  mapping:
    title:
      type: integer
      label: 'Allow link text'
    link_type:
      type: integer
      label: 'Allowed link type'

field.value.citizen_custom:
  type: mapping
  label: 'Default value'
  mapping:
    title:
      type: label
      label: 'Link text'
    url:
      type: string
      label: 'URL'
    options:
      type: mapping
      label: 'Citizen Custom Link options'
      mapping:
        query:
          type: sequence
          label: 'URL query key value pairs'
          sequence:
            type: string
        fragment:
          type: string
          label: 'URL fragment'
        absolute:
          type: boolean
          label: 'Is this URL absolute'
        https:
          type: boolean
          label: 'If the URL should use a secure protocol'
        attributes:
          type: sequence
          label: 'Link attributes'
          sequence:
            type: string
    alias:
      type: string
      label: 'Alias'
